# Generated by Django 5.2.12 on 2026-07-20 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_currency_and_more'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='temp_password',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='business.business'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='business',
            field=models.ForeignKey(help_text='The business this staff member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='business.business'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='user',
            field=models.ForeignKey(help_text='The user who is a staff member', on_delete=django.db.models.deletion.CASCADE, related_name='staff_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'business')},
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['token'], name='staff_invit_token_e4e31b_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email'], name='staff_invit_email_d9b0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['business', 'status'], name='staff_staff_busines_20b34e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['user', 'business'], name='staff_staff_user_id_5368bf_idx'),
        ),
    ]
