# Generated by Django 5.2.12 on 2026-09-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_invitation_options_alter_staffmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='permission_level',
            field=models.CharField(choices=[('managerial_access', 'Managerial Access'), ('limited_access', 'Limited Access')], default='limited_access', max_length=20),
        ),
    ]
