# staff/views.py
import logging
from decimal import Decimal
from rest_framework import viewsets, status, permissions
from rest_framework.decorators import action
from rest_framework.response import Response
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.conf import settings

from business.models import Business
from documents.models import Document
from staff.services import get_full_staff_data
from .models import StaffMember, Invitation
from .serializers import (
    StaffMemberSerializer,
    StaffMemberListSerializer,
    StaffMemberUpdateSerializer,
    CreateStaffSerializer,
    InvitationSerializer,
    CreateInvitationSerializer,
    AcceptInvitationSerializer,
    InviteStaffSerializer,
    AcceptInviteSerializer,
)

User = get_user_model()
logger = logging.getLogger(__name__)


class StaffViewSet(viewsets.ModelViewSet):
    """
    ViewSet for Staff management.

    Standard REST endpoints (auto-generated by ModelViewSet):
      GET    /api/staff/          — list (owner: their staff; staff: themselves)
      GET    /api/staff/{id}/     — retrieve (scoped the same way)
      PATCH  /api/staff/{id}/     — owner-only: edit department/permission_level
      POST   /api/staff/          — disabled; use create_staff/ instead
      DELETE /api/staff/{id}/     — disabled; use deactivate/{id}/ instead

    Custom actions below handle account creation (with temp password),
    invitations, and the staff member's own dashboard.
    """
    permission_classes = [permissions.IsAuthenticated]

    def get_serializer_class(self):
        if self.action == 'create_staff':
            return CreateStaffSerializer
        elif self.action == 'invite':
            return CreateInvitationSerializer
        elif self.action == 'accept_invite':
            return AcceptInvitationSerializer
        elif self.action == 'list':
            return StaffMemberListSerializer
        elif self.action in ('update', 'partial_update'):
            return StaffMemberUpdateSerializer
        return StaffMemberSerializer

    def get_queryset(self):
        """Get appropriate staff queryset based on user role"""
        user = self.request.user

        if user.is_staff:  # Django admin sees all staff
            return StaffMember.objects.all()
        elif user.role == 'owner' and hasattr(user, 'business'):  # Owner sees their staff
            return StaffMember.objects.filter(business=user.business)
        elif user.role == 'staff':  # Staff sees only themselves
            return StaffMember.objects.filter(user=user)

        return StaffMember.objects.none()

    # ── Disable default create/destroy — both go through dedicated flows ──────
    def create(self, request, *args, **kwargs):
        return Response(
            {'error': 'Use POST /api/staff/create_staff/ to create a new staff account.'},
            status=status.HTTP_405_METHOD_NOT_ALLOWED,
        )

    def destroy(self, request, *args, **kwargs):
        return Response(
            {'error': 'Staff accounts cannot be deleted. Use POST /api/staff/deactivate/{id}/ instead.'},
            status=status.HTTP_405_METHOD_NOT_ALLOWED,
        )

    # ── Owner-only edit of department/permission_level ─────────────────────────
    # get_queryset() already scopes an owner's update target to their own
    # business's staff (get_object() 404s otherwise) — this only needs to
    # additionally check that the requester is actually an owner, so a
    # staff member can't PATCH their own or a coworker's record.
    def update(self, request, *args, **kwargs):
        if request.user.role != 'owner' and not request.user.is_superuser:
            return Response(
                {'error': 'Only business owners can update staff details.'},
                status=status.HTTP_403_FORBIDDEN,
            )
        return super().update(request, *args, **kwargs)

    def partial_update(self, request, *args, **kwargs):
        if request.user.role != 'owner' and not request.user.is_superuser:
            return Response(
                {'error': 'Only business owners can update staff details.'},
                status=status.HTTP_403_FORBIDDEN,
            )
        return super().partial_update(request, *args, **kwargs)

    # ========== CREATE STAFF ==========
    @action(detail=False, methods=['post'])
    def create_staff(self, request):
        """
        POST /api/staff/create_staff/

        Owner creates staff account with placeholder password.
        Staff will be prompted to change password on first login.

        Response always reports whether the onboarding email actually
        sent. If it didn't, the temp password is included directly in
        the response so the owner can hand it to the staff member
        manually — previously that email failure was swallowed with no
        signal and no way to recover the password.
        """
        if request.user.role != 'owner':
            return Response(
                {'error': 'Only business owners can create staff.'},
                status=status.HTTP_403_FORBIDDEN
            )

        if not hasattr(request.user, 'business'):
            return Response(
                {'error': 'Owner must have a business.'},
                status=status.HTTP_400_BAD_REQUEST
            )

        serializer = CreateStaffSerializer(
            data=request.data,
            context={'request': request}
        )
        serializer.is_valid(raise_exception=True)
        staff_member = serializer.save()  # CreateStaffSerializer.create() returns the StaffMember
        user = staff_member.user          # the actual User, needed for the email

        email_sent = self._send_onboarding_email(user)

        response_data = {
            'message': (
                'Staff account created. Onboarding email sent.'
                if email_sent else
                'Staff account created, but the onboarding email failed to send. '
                'Share the temporary password with the staff member directly.'
            ),
            'email_sent': email_sent,
            'staff': StaffMemberSerializer(staff_member).data,
        }
        if not email_sent:
            response_data['temp_password'] = staff_member.temp_password

        return Response(response_data, status=status.HTTP_201_CREATED)

    # ========== INVITE STAFF (Email-based) ==========
    @action(detail=False, methods=['post'])
    def invite(self, request):
        """
        POST /api/staff/invite/

        Owner invites staff member via email link.
        """
        if request.user.role != 'owner':
            return Response(
                {'error': 'Only owners can invite staff.'},
                status=status.HTTP_403_FORBIDDEN
            )

        if not hasattr(request.user, 'business'):
            return Response(
                {'error': 'Owner must have a business.'},
                status=status.HTTP_400_BAD_REQUEST
            )

        serializer = CreateInvitationSerializer(
            data=request.data,
            context={'request': request}
        )
        serializer.is_valid(raise_exception=True)
        invitation = serializer.save()

        email_sent = self._send_invitation_email(invitation)

        return Response({
            'message': 'Invitation sent.' if email_sent else 'Invitation created, but the email failed to send.',
            'email_sent': email_sent,
            'email': invitation.email,
            'token': invitation.token,
        }, status=status.HTTP_201_CREATED)

    # ========== ACCEPT INVITATION ==========
    @action(detail=False, methods=['post'], permission_classes=[permissions.AllowAny])
    def accept_invite(self, request):
        """
        POST /api/staff/accept_invite/

        Staff accepts invitation and creates account with password.
        """
        serializer = AcceptInvitationSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()

        return Response({
            'message': 'Account created successfully. Please log in.',
            'user': {
                'id': str(user.id),
                'email': user.email,
                'first_name': user.first_name,
            }
        }, status=status.HTTP_201_CREATED)

    # ========== STAFF DASHBOARD ==========
    @action(detail=False, methods=['get'], url_path='me/dashboard')
    def staff_dashboard(self, request):
        """
        GET /api/staff/me/dashboard/

        Staff member views their dashboard with statistics.
        """
        if request.user.role != 'staff':
            return Response(
                {'error': 'Access denied. Not a staff member.'},
                status=status.HTTP_403_FORBIDDEN
            )

        try:
            staff = StaffMember.objects.get(user=request.user)
        except StaffMember.DoesNotExist:
            return Response(
                {'error': 'Staff profile not found.'},
                status=status.HTTP_404_NOT_FOUND
            )

        data = get_full_staff_data(staff)
        return Response(data)

    # ========== DEACTIVATE STAFF ==========
    @action(detail=False, methods=['post'], url_path='deactivate/(?P<staff_id>[^/.]+)')
    def deactivate(self, request, staff_id=None):
        """
        POST /api/staff/deactivate/{staff_id}/

        Owner deactivates a staff member.
        """
        if request.user.role != 'owner':
            return Response(
                {'error': 'Only owners can deactivate staff.'},
                status=status.HTTP_403_FORBIDDEN
            )

        try:
            staff = StaffMember.objects.get(
                id=staff_id,
                business=request.user.business
            )
        except StaffMember.DoesNotExist:
            return Response(
                {'error': 'Staff member not found.'},
                status=status.HTTP_404_NOT_FOUND
            )

        staff.status = 'inactive'
        staff.save()

        return Response({'message': 'Staff member deactivated.'})

    # ========== ACTIVATE STAFF ==========
    @action(detail=False, methods=['post'], url_path='activate/(?P<staff_id>[^/.]+)')
    def activate(self, request, staff_id=None):
        """
        POST /api/staff/activate/{staff_id}/

        Owner activates a staff member.
        """
        if request.user.role != 'owner':
            return Response(
                {'error': 'Only owners can activate staff.'},
                status=status.HTTP_403_FORBIDDEN
            )

        try:
            staff = StaffMember.objects.get(
                id=staff_id,
                business=request.user.business
            )
        except StaffMember.DoesNotExist:
            return Response(
                {'error': 'Staff member not found.'},
                status=status.HTTP_404_NOT_FOUND
            )

        staff.status = 'active'
        staff.save()

        return Response({'message': 'Staff member activated.'})

    # ========== HELPER METHODS ==========
    def _send_onboarding_email(self, user) -> bool:
        """Send onboarding email to new staff. Returns True on success,
        False on failure — never raises, but never silently disappears
        either; callers use the return value to decide whether to
        surface the temp password directly."""
        business = user.staff_accounts.first().business if user.staff_accounts.exists() else None

        subject = "Welcome to your account!"
        message = f"""
        Hello {user.first_name},

        Your account has been created at {business.name if business else 'our platform'}.

        Please log in using your email.
        On your first login, you will be required to change your password.

        Email: {user.email}

        Best regards,
        {business.name if business else 'The Team'}
        """

        try:
            send_mail(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,
                [user.email],
                fail_silently=False,
            )
            return True
        except Exception as e:
            logger.error(f"Onboarding email failed to send to {user.email}: {e}")
            return False

    def _send_invitation_email(self, invitation) -> bool:
        """Send invitation email to prospective staff. Returns True/False,
        same contract as _send_onboarding_email."""
        accept_link = f"{settings.FRONTEND_URL}/accept-invitation?token={invitation.token}"

        subject = f"You're invited to join {invitation.business.name}!"
        message = f"""
        Hello,

        You've been invited to join {invitation.business.name}.

        Click the link below to accept the invitation and create your account:
        {accept_link}

        This link will expire in 30 days.

        Best regards,
        {invitation.business.name}
        """

        try:
            send_mail(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,
                [invitation.email],
                fail_silently=False,
            )
            return True
        except Exception as e:
            logger.error(f"Invitation email failed to send to {invitation.email}: {e}")
            return False
        
        
        
        # ========== LIST PENDING INVITATIONS ==========
    
    @action(detail=False, methods=['get'], url_path='invitations')
    def invitations(self, request):
        """
        GET /api/staff/invitations/

        Owner-only: every unaccepted invitation for their business.
        """
        if request.user.role != 'owner':
            return Response(
                {'error': 'Only business owners can view invitations.'},
                status=status.HTTP_403_FORBIDDEN
            )
        if not hasattr(request.user, 'business'):
            return Response(
                {'error': 'Owner must have a business.'},
                status=status.HTTP_400_BAD_REQUEST
            )

        pending = Invitation.objects.filter(
            business=request.user.business,
            is_accepted=False,
        ).order_by('-created_at')
        return Response(InvitationSerializer(pending, many=True).data)

    # ========== RESEND INVITATION ==========
    @action(detail=False, methods=['post'], url_path='invitations/(?P<invitation_id>[^/.]+)/resend')
    def resend_invitation(self, request, invitation_id=None):
        """
        POST /api/staff/invitations/{invitation_id}/resend/

        Owner-only: re-sends the existing invitation email using the
        same token (no regeneration — the original link keeps working).
        """
        if request.user.role != 'owner':
            return Response(
                {'error': 'Only business owners can resend invitations.'},
                status=status.HTTP_403_FORBIDDEN
            )

        try:
            invitation = Invitation.objects.get(
                id=invitation_id,
                business=request.user.business,
                is_accepted=False,
            )
        except Invitation.DoesNotExist:
            return Response(
                {'error': 'Invitation not found.'},
                status=status.HTTP_404_NOT_FOUND
            )

        email_sent = self._send_invitation_email(invitation)
        return Response({
            'message': 'Invitation resent.' if email_sent else 'Resend failed — the email could not be sent.',
            'email_sent': email_sent,
        })

    # ========== CANCEL INVITATION ==========
    @action(detail=False, methods=['post'], url_path='invitations/(?P<invitation_id>[^/.]+)/cancel')
    def cancel_invitation(self, request, invitation_id=None):
        """
        POST /api/staff/invitations/{invitation_id}/cancel/

        Owner-only: permanently removes an unaccepted invitation. There's
        no "cancelled" state on the model — this deletes the row outright,
        so the token stops working immediately.
        """
        if request.user.role != 'owner':
            return Response(
                {'error': 'Only business owners can cancel invitations.'},
                status=status.HTTP_403_FORBIDDEN
            )

        try:
            invitation = Invitation.objects.get(
                id=invitation_id,
                business=request.user.business,
                is_accepted=False,
            )
        except Invitation.DoesNotExist:
            return Response(
                {'error': 'Invitation not found.'},
                status=status.HTTP_404_NOT_FOUND
            )

        invitation.delete()
        return Response({'message': 'Invitation cancelled.'})    