# Generated by Django 5.2.12 on 2026-05-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Business Owner'), ('staff', 'Staff'), ('admin', 'Admin')], default='owner', max_length=20),
        ),
    ]
