# Generated by Django 5.2.12 on 2026-06-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_role_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_currency',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(default='#1b2e5e', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='passcode_set',
            field=models.BooleanField(default=False),
        ),
    ]
