# Generated by Django 5.2.12 on 2026-06-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_default_currency_user_avatar_color_and_more'),
        ('accounts', '0003_update_passcode_field'),
    ]

    operations = [
    ]
