# Generated by Django 5.2.12 on 2026-06-17 01:35

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260617_0234'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passcode_set',
        ),
    ]
