# Generated by Django 5.2.12 on 2026-09-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Business Owner'), ('staff', 'Staff')], default='owner', max_length=20),
        ),
    ]
