# Generated by Django 5.2.12 on 2026-05-19 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_add_staffmember_model'),
        ('products', '0001_create_product_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('sale_confirmed', 'Sale Confirmed'), ('sale_delivered', 'Sale Delivered'), ('sale_cancelled', 'Sale Cancelled'), ('purchase_received', 'Purchase Received'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reference_document_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='business.business')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='inventory_i_product_2e3433_idx'), models.Index(fields=['business', 'created_at'], name='inventory_i_busines_46b85b_idx')],
            },
        ),
    ]
