# Generated by Django 5.2.12 on 2026-07-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_create_inventorytransaction_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase_received', 'Purchase Received'), ('adjustment', 'Adjustment'), ('sales_confirmed', 'Sales Confirmed')], max_length=20),
        ),
    ]
