# Generated by Django 5.2.12 on 2026-05-19 14:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_add_staffmember_model'),
        ('customers', '0001_create_customer_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('purchase_invoice', 'Purchase Invoice'), ('proforma_invoice', 'Proforma Invoice'), ('sales_invoice', 'Sales Invoice'), ('receipt', 'Receipt')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('document_date', models.DateField()),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overpaid', 'Overpaid')], default='unpaid', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='business.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='customers.customer')),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
                'indexes': [models.Index(fields=['business'], name='documents_d_busines_3318ee_idx'), models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['status'], name='documents_d_status_07369e_idx'), models.Index(fields=['payment_status'], name='documents_d_payment_9198b9_idx'), models.Index(fields=['sync_status'], name='documents_d_sync_st_275f6b_idx'), models.Index(fields=['-document_date'], name='documents_d_documen_b49160_idx')],
                'unique_together': {('business', 'document_number', 'document_type')},
            },
        ),
    ]
