# Generated by Django 5.2.12 on 2026-06-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_receipt_document_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_sync_st_275f6b_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='sync_status',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('purchase_invoice', 'Purchase Invoice'), ('proforma_invoice', 'Proforma Invoice'), ('sales_invoice', 'Sales Invoice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('unpaid', 'unpaid')], default='paid', max_length=20),
        ),
    ]
