# Generated by Django 5.2.12 on 2026-07-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_documents_d_sync_st_275f6b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_payment_9198b9_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('delivered', 'Delivered'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
    ]
