# Generated by Django 5.2.12 on 2026-07-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_document_documents_d_payment_9198b9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='currency',
            field=models.CharField(default='₦', max_length=10),
        ),
    ]
