# Generated by Django 5.2.12 on 2026-07-27 01:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=5),
        ),
    ]
