# Generated by Django 5.2.12 on 2026-07-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_create_customer_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['full_name']},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
