# Generated by Django 5.2.12 on 2026-06-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_add_staffmember_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
