# Generated by Django 5.2.12 on 2026-07-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_staffmember_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(default='₦', max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='selected_template_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='signature_type',
            field=models.CharField(choices=[('none', 'none'), ('text', 'text'), ('image', 'image')], default='none'),
        ),
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
